# permissions for end users to view redissingles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redissingle-viewer-role
rules:
- apiGroups:
  - testop.yylover.com
  resources:
  - redissingles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testop.yylover.com
  resources:
  - redissingles/status
  verbs:
  - get
